POST https://what-the-health.onrender.com/symptoms/create  HTTP/1.1
content-type: application/json

{
    "name" : "dor de cabeca",
    "description" : "dor de cabeca",
    "medication" : "dorflex",
    "startDate": "2021-04-01",
    "endDate": "2021-05-01",
    "user_id": "7340db54-07b4-4608-8ad4-c7cf9755566e"
}