POST https://what-the-health.onrender.com/symptoms/create  HTTP/1.1
content-type: application/json

{
    "name" : "dor de cabeca",
    "description" : "dor de cabeca",
    "medication" : "dorflex",
    "startDate": "2021-04-01",
    "endDate": "2021-05-01",
    "user_id": "b4eb87c0-efd5-478f-b121-31cabd7bd739"
}