POST https://what-the-health.onrender.com/info/create  HTTP/1.1
content-type: application/json

{
    "altura": 1.80, 
    "peso": 37.0, 
    "idade": 20,
    "user_id": "b4eb87c0-efd5-478f-b121-31cabd7bd739"
}