POST https://what-the-health.onrender.com/info/create  HTTP/1.1
content-type: application/json

{
    "altura": 1.80, 
    "peso": 37.0, 
    "idade": 20,
    "user_id": "ca696a03-6922-4ef2-99cf-9e35b2cf924f"
}